name: Maven Build and Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Clean Project
      run: mvn clean

    - name: Package WAR from submodule
      run: mvn package --file webapp/pom.xml

    - name: List build output
      run: |
        echo "Current directory: $(pwd)"
        ls -lah
        echo "Contents o
